@Backend_HostAddress = http://localhost:5108

### Create account
POST {{Backend_HostAddress}}/Api/Accounts/create
Content-Type: application/json

{
  "username": "karolis123",
  "password": "test1234"
}

### Login
POST {{Backend_HostAddress}}/Api/Accounts/login
Content-Type: application/json

{
  "username": "karolis123",
  "password": "test1234"
}

### Delete account
DELETE {{Backend_HostAddress}}/Api/Accounts/delete/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjUiLCJleHAiOjE3ODg5NzEzNjEsImlzcyI6IlRva2VuQXJjYWRlIiwiYXVkIjoiVG9rZW5BcmNhZGUifQ.yypj5DyU_FErFL2FIrWSQuIjYAczTs-HqLI-So0tZf8