@HostAddress = http://localhost:5108

### Get display name
GET {{HostAddress}}/Accounts/getname
Content-Type: application/json
{
  "username": "karolis123"
}

### Register
POST {{HostAddress}}/Accounts/register
Content-Type: application/json

{
  "displayName": "Karolis",
  "username": "karolis123",
  "password": "test1234"
}

### Login
POST {{HostAddress}}/Accounts/login
Content-Type: application/json

{
  "username": "karolis123",
  "password": "test1234"
}

### Change display name
POST {{HostAddress}}/Accounts/changename
Content-Type: application/json

{
  "username": "karolis123",
  "password": "test1234",
  "newName": "Karolis"
}

### Change password
POST {{HostAddress}}/Accounts/changepass
Content-Type: application/json

{
  "username": "karolis123",
  "oldPassword": "test1234",
  "newPassword": "newPassword1"
}

### Delete account
DELETE {{HostAddress}}/Accounts/delete
Content-Type: application/json

{
  "username": "karolis123",
  "password": "newPassword1"
}
###