@HostAddress = http://localhost:5108

### Get display name
GET {{HostAddress}}/Accounts/getname?username=karolis123

### Register
POST {{HostAddress}}/Accounts/register
Content-Type: application/json

{
  "displayName": "Karolis",
  "username": "karolis123",
  "password": "test1234"
}

### Login
# Response body contains a token, use it as the Authorization header below
POST {{HostAddress}}/Accounts/login
Content-Type: application/json

{
  "username": "karolis123",
  "password": "test1234"
}

### Change display name
POST {{HostAddress}}/Accounts/changename
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "newName": "Karolis"
}

### Change password
POST {{HostAddress}}/Accounts/changepass
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "test1234",
  "newPassword": "newPassword1"
}

### Logout
POST {{HostAddress}}/Accounts/logout
Authorization: Bearer {{token}}

### Delete account
DELETE {{HostAddress}}/Accounts/delete
Authorization: Bearer {{token}}
###
