// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SportMatch.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006111121_AddGamesTable")]
    partial class AddGamesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Backend.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FootballFieldId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("JoinedUsernames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FootballFieldId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Data.SportField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekdayCloseTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekdayOpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekendCloseTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekendOpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SportFields");
                });

            modelBuilder.Entity("Backend.Data.Game", b =>
                {
                    b.HasOne("Backend.Data.SportField", "FootballField")
                        .WithMany()
                        .HasForeignKey("FootballFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballField");
                });
#pragma warning restore 612, 618
        }
    }
}
